[
    ['Node.Js', <FaNodeJs />],
    ['React.js', <FaReact />],
    ['React Native', <FaMobileAlt />],
    ['MySQL', <SiMysql />],
    ['MSSQL', <SiMicrosoftsqlserver />],
    ['JavaScript', <SiJavascript />],
    ['HTML', <FaHtml5 />],
    ['CSS', <FaCss3 />],
    ['TypeScript', <SiTypescript />],
    ['Styled Components', <FaFileCode />],
    ['Tailwind CSS', <FaWind />],
    ['Bootstrap', <FaBootstrap />],
    ['SASS', <FaSass />],
    ['Python', <FaPython />],
    ['Git', <FaGitAlt />],
    ['Power BI', <FaChartBar />],
    ['Microsoft Excel', <FaFileExcel />],
  ]